### ISSUE TITLE
启动界面识别问题依旧

### ISSUE THREAD

**Issue by SxzCaky** [MaaXYZ/M9A#100]
1.5.0版本启动游戏仍然卡在START界面
手动点START之后也不会继续运行
感谢大佬的孜孜不倦♡
![1717114721397](https://github.com/MaaXYZ/M9A/assets/90321454/3ab4bd12-0c54-45f3-b9cd-468f50206f58)
[maa.log](https://github.com/user-attachments/files/15506904/maa.log)

**Comment by a16797** [comment]
你把M9A\config\maa_option.json里的"save_draw": false改成"save_draw": true，保存，然后重启脚本到登录界面，然后关闭脚本。
把整个debug文件打包发上来。文件估计百来兆，可以加下QQ群发到群里

**Comment by SHAventurine** [comment]
俺也一样...而且重装APK也不行气得我直接**重装模拟器**（去1999官网下了它的mumu模拟器桌面版）现在能用了...不知道为什么...你要不试试？

**Comment by MistEO** [comment]
> 俺也一样...而且重装APK也不行气得我直接**重装模拟器**（去1999官网下了它的mumu模拟器桌面版）现在能用了...不知道为什么...你要不试试？

有这功夫为什么不像楼上说的把 debug 文件夹抓一下呢
