### ISSUE TITLE
这个开始了没有反应啊

### ISSUE THREAD

**Issue by Lyduck** [MaaXYZ/M9A#104]
![QQ截图20240602131428](https://github.com/MaaXYZ/M9A/assets/171469120/813ada1b-7569-4d57-ba81-d3626ad21818)

**Comment by Tohkahb** [comment]
重新打开还是不行吗，还是不行的话把debug文件夹中的maa.log发一下

**Comment by CAIBI201** [comment]
我也遇到了这个问题，请问具体解决方案为？

**Comment by CAIBI201** [comment]
> 我也遇到了这个问题，请问具体解决方案为？

没事了，是后台保活的问题
我成功解决了它
