### ISSUE TITLE
使用雷电模拟器可以正常使用,使用mumu的话启动完游戏就没反应了

### ISSUE THREAD

**Issue by 124959377** [MaaXYZ/M9A#108]
![QQ截图20240606144447](https://github.com/MaaXYZ/M9A/assets/36677485/3071628f-a93d-4f7f-b937-5442f3cf6a0a)
[maa.log](https://github.com/user-attachments/files/15604914/maa.log)

**Comment by lamb203** [comment]
你是不是开了MuMu的后台强制保活

**Comment by lamb203** [comment]
看你log还能OCR到QQ

**Comment by lamb203** [comment]
https://github.com/MaaXYZ/MaaFramework/issues/243
之前看到的

**Comment by lamb203** [comment]
https://github.com/MaaXYZ/MaaFramework/issues/243
之前看到的

**Comment by MistEO** [comment]
mumu 设置里的后台保活关一下

**Comment by 124959377** [comment]
感谢大家 关闭后台保活后完美运行
