### ISSUE TITLE
丰收时令4识别错误，会打利齿子的第四关

### ISSUE THREAD

**Issue by 2407135388** [MaaXYZ/M9A#109]

**Comment by 2407135388** [comment]
![Uploading 1999.png…]()

**Comment by 2407135388** [comment]
Resource:

        官服

Tasks:

        - 启动游戏
        - 收取荒原
        - 每日心相（意志解析）
        - 领取奖励
        - 常规作战
                - 作战关卡: 丰收时令 04
                - 复现次数: x4
                - 刷完全部体力: Yes
                - 吃全部临期糖: Yes

### Select action ###

        1. Switch controller
        2. Switch resource
        3. Add task
        4. Move task
        5. Delete task
        6. Run tasks
        7. Exit

会直接打铸币美学04

**Comment by lamb203** [comment]
确实有问题，interface传入的参数错了

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/M9A/pull/111 fixed
