### ISSUE TITLE
No device found!

### ISSUE THREAD

**Issue by jysx0** [MaaXYZ/M9A#121]
![e7a08ccf9bb4fe3e0b5ffcab8649b07](https://github.com/MaaXYZ/M9A/assets/165752877/55f5bdf2-7c65-49f8-8e5e-c7de7aa96299)
突然用不了，应该是找不到adb，但是maa还是能正常用的

**Comment by jysx0** [comment]
[Uploading maa.log…]()

**Comment by jysx0** [comment]
[Uploading maa.log…]()

**Comment by jysx0** [comment]
能看到log吗，一直显示uploading

**Comment by MistEO** [comment]
看不到，uploading 说明没传完，多等一会

**Comment by jysx0** [comment]
[Uploading maa.log…]()

**Comment by MistEO** [comment]
是在点 comment 之前多等一会。。

**Comment by jysx0** [comment]
[maa.log](https://github.com/user-attachments/files/16024537/maa.log)
抱歉😂
