### ISSUE TITLE
1.8.1无法在mumu 3.9.2(3069)上执行

### ISSUE THREAD

**Issue by l0rraine** [MaaXYZ/M9A#128]
可以连接到模拟器，但是启动起来后无法进行任何操作，只是在开始那发呆

**Comment by MistEO** [comment]
把 mumu 设置里的后台保活功能关了试试

**Comment by l0rraine** [comment]
> 把 mumu 设置里的后台保活功能关了试试

感恩，是这个的原因，谢谢。
