### ISSUE TITLE
国际服肉鸽活动卡住无法推进

### ISSUE THREAD

**Issue by waynezh** [MaaXYZ/M9A#130]
M9A ver: M9A-win-x86_64-v1.8.1
模拟器: mumu 12

国际服肉鸽：山麓的回音无法完成，打完1/8之后，卡在如下图的地方。难道国际服文字更改了？

![EITM_放弃奖励_478_2024 07 05-20 18 43 9001357](https://github.com/MaaXYZ/M9A/assets/7220128/c5d10aa1-da5b-4c06-b0b5-cea6fd8fb298)

另外，肉鸽活动的挂机逻辑是反复刷第一个房间吗？

**Comment by waynezh** [comment]
测试了下，好像就是一直刷第一个房间。把`\resource\base\image\Combat\Activity\EchoesinInTheMountain` 替换了一下，暂时解决问题了 😄 
![放弃奖励](https://github.com/MaaXYZ/M9A/assets/7220128/8d15ef06-2518-48f0-9b46-2eaf9742ca39)

**Comment by a16797** [comment]
嗯 就是刷第一个房间
