### ISSUE TITLE
启动任务后无法进行模拟触控

### ISSUE THREAD

**Issue by sloth766** [MaaXYZ/M9A#133]
maa可以进行模拟触控，但是M9A不能运行除启动游戏之外的任务，应该不是adb问题。且“启动游戏”任务之后 命令框会卡住 只能重启exe才能重新设置任务

**Comment by sloth766** [comment]
[Uploading maa.log…]()

**Comment by MistEO** [comment]
log 没发上来，再传一下，等 uploading 没了再点 comment

**Comment by sloth766** [comment]
[maa.log](https://github.com/user-attachments/files/16132656/maa.log)

**Comment by sloth766** [comment]
> log 没发上来，再传一下，等 uploading 没了再点 comment

[maa.log](https://github.com/user-attachments/files/16132670/maa.log)
