### ISSUE TITLE
清理快要到期的体力糖，会把没有临期的一起吃掉，如果吃到达体力上限会一直尝试吃体力并且卡住

### ISSUE THREAD

**Issue by ly5519** [MaaXYZ/M9A#136]
![image](https://github.com/user-attachments/assets/ec39a5ae-c0fb-4406-85e7-5459c5bf8f4e)

**Comment by ly5519** [comment]
[maa.log](https://github.com/user-attachments/files/16227779/maa.log)

**Comment by ly5519** [comment]
希望标记为FATAL等级问题，会乱吃用户存的体力糖🤦‍

**Comment by dongwlin** [comment]
> [maa.log](https://github.com/user-attachments/files/16227779/maa.log)
> 
> 时间在 7月14号22：30左右

这个时间段的日志确实有在吃糖页面，但日志里没有执行“确认吃糖”，只是一直在点击糖，且没有识别到确认界面。你是否有勾选这个“本日登录不再提醒”，可能是勾选这个选项导致没有确认界面直接吃糖。
![image](https://github.com/user-attachments/assets/a00f5b0a-8e9e-49c2-9eb2-73104137805f)

**Comment by ly5519** [comment]
确认是这个问题，今天早上没有跑自动化，睡觉嫌电脑吵就没关机了，今天上来自己先玩了一下，发现到期糖有点多就玩了俩下又换脚本上了

**Comment by ly5519** [comment]
那这个算不算问题，需要改一下吗，不算的话直接关issue了，，如果打勾了本日登录不在提醒是否有办法规避一下

**Comment by dongwlin** [comment]
如果勾选了不再提醒之后吃糖有相对应的提示的话，也许可以增加一个对应的识别来解决这个问题。如果没有的话，只能自行注意了（

**Comment by Tohkahb** [comment]
已修
