### ISSUE TITLE
[bug]: 自动化，遇到活动签到卡住

### ISSUE THREAD

**Issue by ly5519** [MaaXYZ/M9A#137]
![image](https://github.com/user-attachments/assets/d536342d-c37c-4cfc-a906-a07394960a2b)
每日开启脚本时候被卡在这个签到活动页面不动

**Comment by RooobinYe** [comment]
不止，以下是 StartUp 的 bug 补充

当需要更新时，此时又缺少十四行诗的图片时，也会卡住，如下图
![a0c64a5b629d9477766bee97f2702032](https://github.com/user-attachments/assets/388cd113-d05d-49b8-9a45-d1f2e923a8c6)
![bb6ded53a6c0808da6569598f3b931ac](https://github.com/user-attachments/assets/4ebe414b-e18a-458e-81a9-cc5acf4a9c86)

这里可以识别下面的字，当识别到正在更新或者正在加载，可以 sleep 5 秒之类的。

当领取每日签到奖励时，也会卡住
![MuMu12-20240718-122316](https://github.com/user-attachments/assets/2cfa77df-0d2a-41b1-b55e-57124cbaa7c1)
![MuMu12-20240718-122320](https://github.com/user-attachments/assets/ce812cd6-c000-4e8f-a3f6-8db665899300)
这两个活动每次第一次进游戏时会跳出来，就会导致无法识别。

思路是要么识别右上角的「X」号，但是这样就领不到奖励了；

或者开一个兔子（独一律）的图像识别，顺序是从左往右，但是另一个奖励由于每个版本的随机性，很难用类似的方法。

**Comment by ly5519** [comment]
![兔子反馈](https://github.com/user-attachments/assets/ed5fbe0b-a97b-4fde-849f-6aa7232a43eb)
签到其实是有这种引导的，看看是否能利用上

**Comment by a16797** [comment]
> 不止，以下是 StartUp 的 bug 补充
> 
> 当需要更新时，此时又缺少十四行诗的图片时，也会卡住，如下图 ![a0c64a5b629d9477766bee97f2702032](https://private-user-images.githubusercontent.com/104539926/349784040-388cd113-d05d-49b8-9a45-d1f2e923a8c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjY2NTcsIm5iZiI6MTcyNjk2NjM1NywicGF0aCI6Ii8xMDQ1Mzk5MjYvMzQ5Nzg0MDQwLTM4OGNkMTEzLWQwNWQtNDliOC05YTQ1LWQxZjJlOTIzYThjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDUyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDQ2ODYxNDhlOGIzYzNjNWU1MTY1NTEzZmFjODgzOWNlNDQzNzlmMzg1OGRiYjdiYTQ5NGIwMGEwZTJmZjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QqhTKCJapTS8s4IoLbw9c4AEvenv_L6t_hrtLtGx3QQ) ![bb6ded53a6c0808da6569598f3b931ac](https://private-user-images.githubusercontent.com/104539926/349784049-4ebe414b-e18a-458e-81a9-cc5acf4a9c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjY2NTcsIm5iZiI6MTcyNjk2NjM1NywicGF0aCI6Ii8xMDQ1Mzk5MjYvMzQ5Nzg0MDQ5LTRlYmU0MTRiLWUxOGEtNDU4ZS04MWE5LWNjNWFjZjRhOWM4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDUyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWY0M2M4NDdiMTYwODU5YTI4NGNjNTkxYjYwNTVjZjJlMmVkYmE5MDFjMTFkZTYzZGJiZDUxMjYwNmZmY2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6XABo0dcaH80WkpE8qmxZ0LIKrr7NdOzGu1oKt7LWcs)
> 
> 这里可以识别下面的字，当识别到正在更新或者正在加载，可以 sleep 5 秒之类的。
> 
> 当领取每日签到奖励时，也会卡住 ![MuMu12-20240718-122316](https://private-user-images.githubusercontent.com/104539926/349784419-2cfa77df-0d2a-41b1-b55e-57124cbaa7c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjY2NTcsIm5iZiI6MTcyNjk2NjM1NywicGF0aCI6Ii8xMDQ1Mzk5MjYvMzQ5Nzg0NDE5LTJjZmE3N2RmLTBkMmEtNDFiMS1iNTVlLTU3MTI0Y2JhYTdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDUyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWU0MjNiYmRmM2RkYjZlNTc0NTFhNjU5MWQ3NzlkMTZhMTdlMGUxZTExNmE5ZDRiOTM5ZjA5OTkxMGY4YWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PoT6_0ZrqJNfvlS_uzhw-VeT3sfcGFsGdxWQZi9bekk) ![MuMu12-20240718-122320](https://private-user-images.githubusercontent.com/104539926/349784434-ce812cd6-c000-4e8f-a3f6-8db665899300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjY2NTcsIm5iZiI6MTcyNjk2NjM1NywicGF0aCI6Ii8xMDQ1Mzk5MjYvMzQ5Nzg0NDM0LWNlODEyY2Q2LWMwMDAtNGU4Zi1hM2Y2LThkYjY2NTg5OTMwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDUyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjU4OTYzNGVkZmM3MTg4YzI3OTNjNWYwNjAwYzExZGFkZmJkM2IzNzVhMzMxY2RiZDFkOWQ5MWNlMDc5YzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MjpX3YfZx0LPmFYTFogfVCg7991jLt9-64t4cR7rBGw) 这两个活动每次第一次进游戏时会跳出来，就会导致无法识别。
> 
> 思路是要么识别右上角的「X」号，但是这样就领不到奖励了；
> 
> 或者开一个兔子（独一律）的图像识别，顺序是从左往右，但是另一个奖励由于每个版本的随机性，很难用类似的方法。

签到已经可以X掉了。似乎可以识别一下明日可领，然后领前一天的（）

StartUp 感觉可以在GameLoading多加几张图。好像挺久没卡这里了，遇到了再修。

**Comment by a16797** [comment]
签到已经可以X掉了。似乎可以识别一下明日可领，然后领前一天的（）

StartUp 感觉可以在GameLoading多加几张图。好像挺久没卡这里了，遇到了再修。
