### ISSUE TITLE
[feat]: 当选择推当期活动时，可以选择推困难模式

### ISSUE THREAD

**Issue by RooobinYe** [MaaXYZ/M9A#142]
大概逻辑是：当玩家选择推活动的时候，可以选择推故事模式还是困难模式

如果选择了故事模式，就现流程不变；如果选择了困难模式，就在进入地图的基础上再点击一次困难模式。

**Comment by RooobinYe** [comment]
我明天提一个 pr

**Comment by Tohkahb** [comment]
已修
