### ISSUE TITLE
[bug] 邮箱和家园经常陷入卡死

### ISSUE THREAD

**Issue by cel-ti** [MaaXYZ/M9A#150]
1. 特殊类型邮箱容易陷入卡死
2. 家园满好感会陷入卡死

**Comment by Tohkahb** [comment]
能给个截图和log吗

**Comment by cel-ti** [comment]
![image](https://github.com/user-attachments/assets/585c1fa0-bc88-4e79-a87e-8fc101fb938d)

**Comment by cel-ti** [comment]
![image](https://github.com/user-attachments/assets/340350b2-7c57-4342-907b-97b694acae36)
![image](https://github.com/user-attachments/assets/dab7b8a2-fa93-4892-bd98-153d5989820a)

**Comment by a16797** [comment]
新版本还卡家园吗     签到这个等修复
