### ISSUE TITLE
[bug]部分中文字无法显示

### ISSUE THREAD

**Issue by steven12240202** [MaaXYZ/M9A#156]
我的内建windows powershell在运行m9a时虽能正常使用，但有部分中文字无法显示，导致我无法看懂各项数字所支援的功能，猜测可能与我是使用繁中系统有关，但灌了简中语言套件后，依然无法显示，请问这有什麽解决方法吗？

附截图
![螢幕擷取畫面 2024-07-28 170535](https://github.com/user-attachments/assets/e6418792-d5bd-4436-bd98-1ff1e0ade71d)

**Comment by a16797** [comment]
不清楚什么问题。可以加群试试UI版？ 或者试试新版
