### ISSUE TITLE
[bug] 收取荒原角色好感度满 界面点击会卡死

### ISSUE THREAD

**Issue by longshensanjie** [MaaXYZ/M9A#158]
进入荒原角色好感度满时候，界面会点击卡死，下面是截图和 log 文件

![屏幕截图 2024-07-31 110934](https://github.com/user-attachments/assets/293ad31c-a160-4170-a769-96c6d6b7f1ce)
[maa.zip](https://github.com/user-attachments/files/16435773/maa.zip)

**Comment by a16797** [comment]
新版本还卡吗

**Comment by longshensanjie** [comment]
@a16797 最新2.1版本家园不会卡，但是多了魔精生产材料之后会出现收取不完全的情况

**Comment by a16797** [comment]
> @a16797 最新2.1版本家园不会卡，但是多了魔精生产材料之后会出现收取不完全的情况

提供一下进入荒原时的截图，不知道是不是跑到识别区域之外了，我这里都没问题。
还有收集不完全的时候的日志

**Comment by a16797** [comment]
应该没事了 我连着收了一晚上 也没卡。
