### ISSUE TITLE
常规作战不能自动连打画完全部体力

### ISSUE THREAD

**Issue by jysx0** [MaaXYZ/M9A#161]
选择复现次数x4,是否清完全部体力1，是否吃临期药1，但是打完4次就执行下一个任务了，也不会吃临期药
[maa.log](https://github.com/user-attachments/files/16490847/maa.log)
重新下载m9a后问题仍然还在

**Comment by RooobinYe** [comment]
「是否清完全部体力 1，是否吃临期药 1」

指的是当你有20体力时，勾选了复现次数*4，但是需要80体力，此时只会使用20体力复现一次的意思。

是否吃临时药指的是当你不满80体力时，吃药恢复到80体力，打四次就结束了

**Comment by jysx0** [comment]
明白了，感谢解答
