### ISSUE TITLE
刷不完全部体力。

### ISSUE THREAD

**Issue by a16797** [MaaXYZ/M9A#164]
github下载的刷不完体力，ALLIN这里OCR识别不到
![fa97bbb004f01f144c4df80ee4f4776b](https://github.com/user-attachments/assets/52a1c448-6f31-4b43-9399-7bd84dd94d21)

本地install的可以刷完体力。ALLIN这里正常识别。
![7dfaa18cdb9009f14f7080ef50bf2c71](https://github.com/user-attachments/assets/9108a045-e71d-40ef-966a-3e49cec7fc42)

[1.8.6maa.log](https://github.com/user-attachments/files/16568443/1.8.6maa.log)
[本地maa.log](https://github.com/user-attachments/files/16568444/maa.log)

**Comment by yishifengyin** [comment]
我也是发现刷不完体力，看到你的报告后按install的方式安装了一遍，但结果和release的是一样的

**Comment by a16797** [comment]
> 我也是发现刷不完体力，看到你的报告后按install的方式安装了一遍，但结果和release的是一样的

奇了怪了，不知道是什么问题，玛丽救救
