### ISSUE TITLE
[bug]无限startup

### ISSUE THREAD

**Issue by Talloran3999** [MaaXYZ/M9A#166]
打开后无限重复闪烁白底黑字深蓝logo，以下为log
[maa.zip](https://github.com/user-attachments/files/16592857/maa.zip)

**Comment by Talloran3999** [comment]
https://www.bilibili.com/video/BV1ZUYzeEEvq/?vd_source=997d57a52284816cc381418b82e3aaba 具体表现见视频

**Comment by a16797** [comment]
#108

**Comment by MistEO** [comment]
mumu 设置里的后台保活关一下
