### ISSUE TITLE
选择run task后MaaPiCli.exe会关闭，停止运行

### ISSUE THREAD

**Issue by JJW-Glaze** [MaaXYZ/M9A#167]
一开始的adb路径选择自动的时候运行10秒左右就会自己关闭，后面手动添加路径后，选择run task也是等待10秒左右就会自己关闭（路径中用快捷方式是因为原始的adb路径中包含中文，感觉应该不是因为快捷方式吧？）
<img width="371" alt="image" src="https://github.com/user-attachments/assets/fb9faa8a-e15c-414f-abb7-706e6333dc13">

[maa.log](https://github.com/user-attachments/files/16600556/maa.log)

**Comment by JJW-Glaze** [comment]
研究了好久没搞明白，求大佬们教教 XD

**Comment by JJW-Glaze** [comment]
然后关于管理员权限运行，我也尝试了一下，也是相同的结果

**Comment by MistEO** [comment]
你这个 controller 不对，怎么填了个 link。。

**Comment by JJW-Glaze** [comment]
因为原本的路径含中文，好像会识别不了，用了一个快捷方式，如果是因为这个的话，我可以用mklink来解决路径问题吗

**Comment by JJW-Glaze** [comment]
> 你这个 controller 不对，怎么填了个 link。。

因为原本的路径含中文，好像会识别不了，用了一个快捷方式，如果是因为这个运行不了的话，我可以用mklink来解决路径问题吗？而且一开始的自动寻找路径也是运行就结束进程，感觉像是其他的问题

**Comment by Tohkahb** [comment]
不行，重下模拟器吧

**Comment by MistEO** [comment]
> > 你这个 controller 不对，怎么填了个 link。。
> 
> 因为原本的路径含中文，好像会识别不了，用了一个快捷方式，如果是因为这个运行不了的话，我可以用mklink来解决路径问题吗？而且一开始的自动寻找路径也是运行就结束进程，感觉像是其他的问题

先把这个问题解决了，再看新问题，带一下新的 log

**Comment by JJW-Glaze** [comment]
重新下载，没有中文路径后闪退的解决了，可以成功运行了，真的非常感谢大佬们的耐心帮助！！！！
同时我也有点好奇为什么MAA的路径可以含中文，但是M9A的不可以？二者的框架不都是MaaFramework吗？（纯好奇想问，因为是计算机专业的大二在读学生）
