### ISSUE TITLE
发现了一个奇怪的关卡——猪鼻美学

### ISSUE THREAD

**Issue by iblueer** [MaaXYZ/M9A#171]
![PixPin_2024-08-26_19-45-13](https://github.com/user-attachments/assets/085656d2-bc33-491b-81f4-775fa697d97e)

有点奇怪

**Comment by iblueer** [comment]
顺带一提，在2.0.0alpha.2版本中，该关卡名称被修复，但是设定为常规作战对象后，无法正常执行

**Comment by a16797** [comment]
> 顺带一提，在2.0.0alpha.2版本中，该关卡名称被修复，但是设定为常规作战对象后，无法正常执行

为什么不行 说具体一点。我试了下还是可以刷的。

**Comment by iblueer** [comment]
我是安装了2.0.0a2版本后，设定常规作战为 铸币美学 06，然后执行任务。
从模拟器看来，在选择关卡页面会卡住，不向下进行。

**Comment by a16797** [comment]
每日心相刷掉了吗。没刷的话它会把铸币挤到屏幕之外，就识别不到了

**Comment by a16797** [comment]
#186
