### ISSUE TITLE
深眠满星后仍试图运行“自动深眠”

### ISSUE THREAD

**Issue by Loshepherd** [MaaXYZ/M9A#175]
问题描述：如题，在深眠满星后，M9A仍试图运行“自动深眠”

希望添加功能：识别深眠界面右下角进度，决定是否执行“自动深眠”

<details>

<summary>M9A运行截图与log</summary>

![屏幕截图 2024-09-05 114048](https://github.com/user-attachments/assets/20fbefcb-7b4e-4975-be90-c73f9079cdf6)

[maa.log](https://github.com/user-attachments/files/16883696/maa.log)

运行时间为2024/9/5 11:00之后，可以只看对应部分log

</details>

<details>

<summary>1999深眠界面</summary>

![屏幕截图 2024-09-05 114358](https://github.com/user-attachments/assets/7ce2d663-c2a9-430b-b0e1-66647564cb24)

</details>

**Comment by Loshepherd** [comment]
希望添加功能：不执行“自动深眠”，仅“每周领取浅眠域奖励”

**Comment by Windsland52** [comment]
#234 bug 已修复，两个功能也加上了
