### ISSUE TITLE
开始任务时总是要删除data\local\tmp

### ISSUE THREAD

**Issue by luck-ning** [MaaXYZ/M9A#176]
[Uploading maa.log…]()

**Comment by a16797** [comment]
你的日志还没传上来

**Comment by luck-ning** [comment]
[Uploading maa.log…]()

**Comment by luck-ning** [comment]
![image](https://github.com/user-attachments/assets/5ef070e0-2a71-4dfe-8a0a-980484856463)

**Comment by MistEO** [comment]
2.0 应该修掉了？试试看
