### ISSUE TITLE
肉鸽出现新节点导致终止

### ISSUE THREAD

**Issue by LinYanxi0** [MaaXYZ/M9A#177]
<img width="961" alt="{B267D971-D530-4a7a-A288-5922FF14585A}" src="https://github.com/user-attachments/assets/38a0ae06-951e-4927-b35c-d62f8bec1e67">

rt，并附图
目前版本（187）遇到这个情况时会分别点击最后一列第一个，最后一列第二个，当前格，然后报错：
[ERR][Px16584][Tx44156][UnitBase.cpp][L65][MaaNS::CtrlUnitNs::UnitBase::startup_and_read_pipe] child return error [argv.exec=D:/Software/MuMuPlayer-12.0/shell/./adb.exe] [argv.args=["-s","127.0.0.1:16384","shell","rm \"/data/local/tmp/\""]]

**Comment by a16797** [comment]
取消挂载资料片。

只为了刷奖励，没必要打资料片。
