### ISSUE TITLE
不知为何无法运行

### ISSUE THREAD

**Issue by Orchop** [MaaXYZ/M9A#181]
![929516238cd7fd5f44b4384ad9e227ef](https://github.com/user-attachments/assets/53d1521f-50d4-4077-8904-a30bcd143577)
![880adabd53ad1c3529f4c0160a253b13](https://github.com/user-attachments/assets/9934a3bf-7c42-425c-a840-84e4b0b89424)

**Comment by a16797** [comment]
任务空的
