### ISSUE TITLE
[bug] 最新2.1版本的每日心相功能卡死

### ISSUE THREAD

**Issue by longshensanjie** [MaaXYZ/M9A#185]
在最新2.1版本当中，每日心相功能进入资源画面之后会一直持续点击资源这两个字，不再进行其他任何操作

相关 log 添加在附件， 看最后的 log 记录即可
[maa.zip](https://github.com/user-attachments/files/17082608/maa.zip)

顺便反应下前面可能别人反馈过的两个 bug
1. 启动游戏功能，签到页面会阻挡接下来的操作
2. 荒原家园添加魔精之后，如果生产了材料会出现收取其他资源不完全的情况

**Comment by a16797** [comment]
任务安排先刷每日心相再刷其他。

微尘利齿有问题吗，有的话提供一下模拟器截图
![image](https://github.com/user-attachments/assets/771ff1c3-21f1-405c-b6ff-3ea0220e6dae)
![image](https://github.com/user-attachments/assets/7a0e3810-11b1-4912-8717-0071dec282f0)

**Comment by a16797** [comment]
心相卡住的地方提供一个截图

**Comment by a16797** [comment]
#186
