### ISSUE TITLE
Task.Started ActivityEntry无法结束

### ISSUE THREAD

**Issue by zyzephyr44** [MaaXYZ/M9A#187]
一直点击看板娘
![Uploading 屏幕截图 2024-09-21 163959.png…]()

**Comment by zyzephyr44** [comment]
![Uploading 屏幕截图 2024-09-21 163959.png…]()

**Comment by zyzephyr44** [comment]
![屏幕截图 2024-09-21 163959](https://github.com/user-attachments/assets/f1d9610a-70da-46f5-b702-9d2b0552214c)

**Comment by a16797** [comment]
这是啥任务

**Comment by zyzephyr44** [comment]
根据顺序的话，应该是活动刷取

**Comment by a16797** [comment]
你再运行一遍，卡住的时候关闭脚本。然后把日志发上来
