### ISSUE TITLE
[bug] 最新版本大量功能出现bug

### ISSUE THREAD

**Issue by longshensanjie** [MaaXYZ/M9A#190]
最新的版本领取荒原，每日心相，常规战斗，领取奖励均出现问题，具体问题描述如下：

1.领取荒原会卡在魔精的生产页面，如果鼠标退出生产页面则会一直进入，一直到终端提示领取荒原失败进入其他功能
[
![屏幕截图 2024-09-22 111505](https://github.com/user-attachments/assets/599b023d-647b-474d-86a5-fd317d6e82c6)
](url)
2.使用两次每日心相功能，第二次可以正常运行，第一次进去是如下状态，从代理模式点击变成普通模式，然后点击卡死
![屏幕截图 2024-09-22 111050](https://github.com/user-attachments/assets/cb4b8cb4-9613-4675-9dd3-8021ccf0d34c)
![屏幕截图 2024-09-22 111109](https://github.com/user-attachments/assets/2e8c3741-2dca-48f3-9697-104d82993427)
3.常规战斗我选择的是铸币关卡，进入如下界面之后，一直右滑点击，卡死
![屏幕截图 2024-09-22 111600](https://github.com/user-attachments/assets/9a6c61b2-2638-4312-b019-06020f6ea2d6)
4.领取奖励的话，我猜测因为我的用的笔记本性能没那么好，在领取点唱机奖励时候界面有延迟，多次点击本来是领取奖励，多次有延迟之后会点到解锁典藏光碟，进入点唱机页面导致卡死
![屏幕截图 2024-09-22 111748](https://github.com/user-attachments/assets/8a376ce0-3043-41ee-930e-fcea46bd1d7f)
![屏幕截图 2024-09-22 111840](https://github.com/user-attachments/assets/ea92d520-5b35-47c2-a705-9d93383cbd18)

两次的 log 按照顺序放在这里，第一个看最后一次就行，第二个是单独的

[maa.zip](https://github.com/user-attachments/files/17088133/maa.zip)

[maa2.zip](https://github.com/user-attachments/files/17088134/maa2.zip)

**Comment by a16797** [comment]
前几个问题 #189 

点唱机比较麻烦，本身识别就不是很准确，不太好处理

**Comment by longshensanjie** [comment]
@a16797 2.12版本测试过后，领取荒原和常规战斗还是有问题
1.领取荒原还是和之前描述的问题一样，卡在魔精的生产页面直致退出
2.常规战斗选取铸币美学之后，会跳转到资源页面之后持续点击资源按钮卡死

log 如下，看最新的就行
[maa.zip](https://github.com/user-attachments/files/17088712/maa.zip)

**Comment by a16797** [comment]
生产你让脚本自己收。一般来说都有待收取的产品，你收了脚本就找不到了。   有空再完善吧。
铸币你给个截图，卡在哪了

**Comment by longshensanjie** [comment]
@a16797 卡在下图，一直点击资源按钮 
![屏幕截图 2024-09-23 090835](https://github.com/user-attachments/assets/62c7c082-f08a-47a1-a2d9-7aa705484c70)

**Comment by a16797** [comment]
你先自行修改下吧。
M9A\resource\base\pipeline\combat.json里
找到ResourceChapter_MAEnter
把expected里加一个铸
"expected": [
            "铸币",
            "铸"
        ],
![image](https://github.com/user-attachments/assets/d97566a4-403f-4418-867b-aea215b6d42f)

**Comment by longshensanjie** [comment]
@a16797 新版本之前反应的大部分问题已经解决，唯独领取荒原功能还是会卡死在魔精生产界面，微尘和粒子都没领取

详细 log 看最新的一次
[maa.zip](https://github.com/user-attachments/files/17182975/maa.zip)

**Comment by a16797** [comment]
更新一下，应该修了
