### ISSUE TITLE
國際服中黃昏的音序疑似因無法找到自動編隊導致錯誤

### ISSUE THREAD

**Issue by paul0665** [MaaXYZ/M9A#215]
如果手動點選自動編隊可以正常運作
BlueStacks 5.21.301.1005
1920x1080/2560x1440 240/320 DPI皆無法正常識別

[maa.log](https://github.com/user-attachments/files/17293808/maa.log)

![image](https://github.com/user-attachments/assets/406cae2b-542f-47ab-b20e-0c4e9513383e)

![image](https://github.com/user-attachments/assets/5c5e34bb-e53a-490e-9017-d375a3109d02)

**Comment by adamcoussins** [comment]
我也出现了你有解决吗

**Comment by paul0665** [comment]
> 我也出现了你有解决吗

沒有 如果解決就會是close了

**Comment by a16797** [comment]
现在还卡？  你录个像发来，日志也看不明白

**Comment by adamcoussins** [comment]
还是存在的，选人界面不会点击快捷编队选人，然后过了几十秒就会任务已经全部完成，就停止了。


https://github.com/user-attachments/assets/6f14922a-f001-46f6-bb9d-c3f9ab69c085

**Comment by adamcoussins** [comment]
[maa.log](https://github.com/user-attachments/files/17822073/maa.log)
是因为国服的快捷编队更改了位置吗？附上我的log

**Comment by Windsland52** [comment]
https://github.com/MaaXYZ/M9A/actions/runs/11923468128
请试试下载这里对应的m9a，看看问题是否解决

**Comment by paul0665** [comment]
[maa.log](https://github.com/user-attachments/files/17828519/maa.log)
現在是在戰鬥頁面直接結束任務了

![image](https://github.com/user-attachments/assets/638ab33d-5e0e-4af3-a9ae-bf92c57da981)

**Comment by Windsland52** [comment]
ok，找到问题了，而且前面的问题也解决了

**Comment by Windsland52** [comment]
[outside_deduction.json](https://github.com/user-attachments/files/17829043/outside_deduction.json)
先换下这个文件用着吧

**Comment by Windsland52** [comment]
[outside_deduction.json](https://github.com/user-attachments/files/17829098/outside_deduction.json)
先换下这个文件用着吧

**Comment by paul0665** [comment]
目前正常 我先跑個幾小時如果有問題再回報

**Comment by Windsland52** [comment]
再见就是新issue了
