### ISSUE TITLE
2.3.4自动深眠闪退

### ISSUE THREAD

**Issue by thiedx** [MaaXYZ/M9A#224]
MFAWPF 1.2.1.5   M9A 2.3.4
雷电模拟器 
连接正常 其他任务正常 单勾选自动深眠 运行到选上半小人界面MFA无任何提示闪退
![image](https://github.com/user-attachments/assets/3c900782-609e-42a9-8535-ab8ede9aa184)

Log
[maa.log](https://github.com/user-attachments/files/17455506/maa.log)

控制台
![image](https://github.com/user-attachments/assets/13e77dd3-9aef-4f4e-a7f6-145851fdbf20)

**Comment by zhiyu1998** [comment]
这个问题我可以帮解决，我看commit，10月1日植入了一个[目标识别](https://github.com/MaaXYZ/M9A/commit/6148ac8359fa0facc1e5be8563a53c943d057ba9)，但是今天出梦境好像无法正常使用，不知道那位老哥有没有全面测试，反正我打不开，

现在最好的办法就是把`limbo.json`退回到上一个commit就可以解决，如果非要用目标识别我觉得还是要多测试下。

这是修改后的效果：

[limbo.json](https://github.com/MaaXYZ/M9A/commit/6148ac8359fa0facc1e5be8563a53c943d057ba9#diff-f644dbb18008fde4b17d2b72d9b9a932cf175eaaa860796caee03117da9ca52f)

**Comment by a16797** [comment]
先把 gpu 关了。comfig/maa_pi_config.json 里 gpu 改成 -2

**Comment by thiedx** [comment]
> 先把 gpu 关了。comfig/maa_pi_config.json 里 gpu 改成 -2

关闭之后从控制台启动可正常运行，但是用MFAWPF还是闪退

**Comment by lamb203** [comment]
PiCli能用就行

**Comment by thiedx** [comment]
好的 感谢二位
