### ISSUE TITLE
关于更新提示（MFA）的一些问题

### ISSUE THREAD

**Issue by lamb203** [MaaXYZ/M9A#226]
看了下MFA好像能检测资源版本，于是尝试在interface.json文件内添加了仓库地址后，确实能提示版本更新，故想将仓库地址添加进去，但不知道是直接添加至asset的interface里面内呢还是在install.py内添加才好，故开此issue

**Comment by lamb203** [comment]
![image](https://github.com/user-attachments/assets/92202323-f65f-4203-8932-c8319c6f8f83)
![image](https://github.com/user-attachments/assets/343142ff-d6fa-489f-8ddd-90948a5f5e72)
<img width="626" alt="image" src="https://github.com/user-attachments/assets/7797a257-69ee-4746-b9d7-29e3438c5fb2">

**Comment by MistEO** [comment]
固定的值放到 json 里好了，动态的才放到 py 脚本里
