### ISSUE TITLE
希望更新“雨中悬想”自动

### ISSUE THREAD

**Issue by QingWanNiang** [MaaXYZ/M9A#231]
1.回声屿关卡很长，且难度不大，有加入自动必要
![图片](https://github.com/user-attachments/assets/c9e4b648-1ca2-431a-a01a-bbc617123ca0)
如图，手打实在太慢
2.迷思海大部分关卡都能自动，加入也会大幅简化时间

**Comment by lamb203** [comment]
这活动真能自动挂吗，策略类玩法是要换配队的，有几关没特定机制还打不了

**Comment by a16797** [comment]
活动难度太大了。还是自己手动打吧

**Comment by Windsland52** [comment]
轮换时间太久，还是手打吧，目前只考虑做个迷思海“寻思”扫荡

**Comment by Windsland52** [comment]
> 轮换时间太久，还是手打吧，目前只考虑做个迷思海“寻思”扫荡

体验了一下，回声屿还是有做的必要的
