### ISSUE TITLE
常规作战-意志解析功能异常

### ISSUE THREAD

**Issue by cyt0417** [MaaXYZ/M9A#248]
长时间卡在资源界面点击第三扇门，手动把界面拖到右边，露出意志解析入口之后才能正常进入
[Uploading maa.log…]()

**Comment by cyt0417** [comment]
![QQ20241117-181715](https://github.com/user-attachments/assets/3d9d11cf-7819-4c70-ad3c-3a359b067431)

**Comment by cyt0417** [comment]
[maa.log](https://github.com/user-attachments/files/17789862/maa.log)

**Comment by Windsland52** [comment]
这个功能设计的时候就只考虑了刷每日免费的次数，有用体力刷的需求吗

**Comment by a16797** [comment]
#249
