### ISSUE TITLE
完美适配日服资源

### ISSUE THREAD

**Issue by Windsland52** [MaaXYZ/M9A#260]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

仅修改一个包名并不够，会出现启动时重复启动的情况。大概需要替换 `startgame` `download` `BluePochLogo` 三个资源

### 其他内容

待startup重构后再进行
- [x] 增加SOD_Skip任务适配，准备直接在国服改

**Comment by Tohkahb** [comment]
发一下你说的这三个界面对应的截图，进群发或者这里发都可以

**Comment by Windsland52** [comment]
![5(I4`T$2)R%TX5$2 G6UOFG](https://github.com/user-attachments/assets/759a62ea-afaf-4a99-924c-f6be01bac8a6)
增加SOD_Skip任务适配，准备直接在国服改
