### ISSUE TITLE
希望添加黄昏的音序速刷功能(参考b站，bv号在下面)

### ISSUE THREAD

**Issue by twen20010806** [MaaXYZ/M9A#267]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

当前版本2.4.11:点满刻画生长指引之歌后会跳过第一关的战斗，因此可以做到速刷第一关，过了第一关之后可以获得一个信物。大致只需要两分钟一个信物。bv号https://www.bilibili.com/video/BV1w1421C775

### 有什么好的想法？

在局外演绎添加设置，设置速刷或者通关选项。

### 其他内容

![a9bc7c57-199a-4b8b-ac32-0ffd9041a71c](https://github.com/user-attachments/assets/2a472309-5d44-459f-bcb0-c1ef88ad6672)

**Comment by Windsland52** [comment]
completed in https://github.com/MaaXYZ/M9A/pull/269
