### ISSUE TITLE
黄昏的音序任务进行时自动结束任务

### ISSUE THREAD

**Issue by Phyrance** [MaaXYZ/M9A#268]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

黄昏的音序任务进行时自动结束任务

### Version

v2.4.12

### 日志和配置文件

[maa.log](https://github.com/user-attachments/files/18016268/maa.log)
[config.json](https://github.com/user-attachments/files/18016270/config.json)
08:15:27
08:58:45

### 配置信息

Windows1022H2    MuMu    1600*900(DPI 240)    240FPS

GPU加速开启    RTX4070 Super

**Comment by Windsland52** [comment]
08:15:27
08:58:45
这俩时间是干啥的

**Comment by Windsland52** [comment]
哦没事了，是两个timeout
