### ISSUE TITLE
”切换账号“功能在账号选择界面出错

### ISSUE THREAD

**Issue by Loshepherd** [MaaXYZ/M9A#287]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

执行”切换账号“任务时，退出登录后停留在选择账号界面（如截图），直至任务超时

### Version

v2.5.6
使用MaaPiCli

### 日志和配置文件

在Task1: SwitchAccount 功能Failed之后手动退出了账号，以下为日志及配置
[maa.log](https://github.com/user-attachments/files/18220848/maa.log)
[maa_pi_config.json](https://github.com/user-attachments/files/18220850/maa_pi_config.json)

### 配置信息

操作系统：Ubuntu24.04
模拟器：Waydroid（分辨率：2560x1440）
GPU加速推理开启（NVIDIA GeForce RTX 3060 Laptop）

### 截图或录屏

任务超时时刻的游戏界面，采用adb截取原图
![SwitchTimeout](https://github.com/user-attachments/assets/18fc6c00-b564-42ea-8015-e777c1aebc35)

### 还有别的吗？

退出登录 功能正常，
点击账号列表 未观察到执行该操作
随后任务超时

**Comment by Windsland52** [comment]
再截个展开列表后，有多个账号的时候的图

**Comment by Loshepherd** [comment]
> 再截个展开列表后，有多个账号的时候的图

![AccountList](https://github.com/user-attachments/assets/a1862e99-cb2d-41ae-b833-9ecfdbe68452)

补充：实际上运行时没能进入这个界面（列表没有展开）

**Comment by Windsland52** [comment]
是，但是鉴于你这个出现的问题，进到这个界面也会出错，后面的任务也需要修改

**Comment by Windsland52** [comment]
这个左下角是什么东西，这图是通过模拟器截的吗

**Comment by Loshepherd** [comment]
> 这个左下角是什么东西，这图是通过模拟器截的吗

是用adb命令截的，应该是LineageOS(Waydroid 默认安卓系统)的导航栏，我试试能不能去掉

**Comment by Windsland52** [comment]
是就没问题了，不用截了

**Comment by Windsland52** [comment]
https://github.com/Windsland52/M9A/actions/runs/12453995953 试下这个

**Comment by Loshepherd** [comment]
> https://github.com/Windsland52/M9A/actions/runs/12453995953 试下这个

试了一下，还是没法进入账号列表
log：
[maa.log](https://github.com/user-attachments/files/18223753/maa.log)

adb截图：
![AccountChangeError2](https://github.com/user-attachments/assets/64cf55a2-f94d-4f4d-8996-62434ed2801a)

**Comment by Loshepherd** [comment]
我最终选择修改模拟器分辨率至1920x1080以适配该功能，也许可以在文档中添加“推荐分辨率”这一项，感谢这两天来的帮助

**Comment by Windsland52** [comment]
https://github.com/MaaXYZ/M9A/blob/main/docs/zh_cn/manual/%E6%96%B0%E6%89%8B%E4%B8%8A%E8%B7%AF.md#6-%E6%AD%A3%E7%A1%AE%E8%AE%BE%E7%BD%AE%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%88%86%E8%BE%A8%E7%8E%87 有写的

**Comment by Windsland52** [comment]
我用的模板也是1280*720截的

**Comment by Windsland52** [comment]
主要是深蓝这个登录框就很奇怪，根据分辨率不同，大小也不一样。

**Comment by Loshepherd** [comment]
> > https://github.com/Windsland52/M9A/actions/runs/12453995953 试下这个
> 
> 这个没有起效吗，我是按照你给的截图加了新的模板

确实没有起效

运行的版本信息为  Version: v2.4.12.beta.2-ci.64-gd06c94b

**Comment by Windsland52** [comment]
那就怪了

**Comment by Windsland52** [comment]
依旧是没点开那个展开的账号列表？

**Comment by Loshepherd** [comment]
> > https://github.com/Windsland52/M9A/actions/runs/12453995953 试下这个
> 
> 试了一下，还是没法进入账号列表 log： [maa.log](https://github.com/user-attachments/files/18223753/maa.log)
> 
> adb截图： ![AccountChangeError2](https://private-user-images.githubusercontent.com/89327296/398021526-64cf55a2-f94d-4f4d-8996-62434ed2801a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjMxODUsIm5iZiI6MTczNTAyMjg4NSwicGF0aCI6Ii84OTMyNzI5Ni8zOTgwMjE1MjYtNjRjZjU1YTItZjk0ZC00ZjRkLTg5OTYtNjI0MzRlZDI4MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA2NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZGZjODdlNmQxMGQyNGQ0ZThjMzUyZDM4NmViNWMzZTVhN2U2Nzg5N2Y4ODlkOTA3OGUzYjIwN2QyYzkwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WBf3vfAikHMsIVpyq2FD5VWit7MJvxoEcUTYhei0hro)

是的，截图如上

**Comment by Windsland52** [comment]
可以改下config下的maa_option.json save draw 改成true，然后再重新运行一遍，将整个debug文件夹打包一下

**Comment by Loshepherd** [comment]
> 可以改下config下的maa_option.json，save_draw 改成true，然后再重新运行一遍，将整个debug文件夹打包一下

压缩包体积过大了，我上传到如下的仓库里了

[Loshepherd/debug](https://github.com/Loshepherd/debug)

**Comment by Windsland52** [comment]
[switch_account.json](https://github.com/user-attachments/files/18238345/switch_account.json)
换一下`resource/base/pipeline/switch_account.json`这个文件，为1440p加了ocr。

**Comment by Loshepherd** [comment]
还是不行，这是新的log与截图

[Loshepherd/debug](https://github.com/Loshepherd/debug)

**Comment by Windsland52** [comment]
第241行换成`"expected": "[v√V]",`呢

**Comment by Windsland52** [comment]
少了中括号

**Comment by Loshepherd** [comment]
> 第241行换成`"expected": "[v√V]",`呢

修改后可以进入账号列表了，但是选择另一个账号时出现问题，log和截图已更新

[Loshepherd/debug](https://github.com/Loshepherd/debug)

**Comment by Windsland52** [comment]
[switch_account.json](https://github.com/user-attachments/files/18239576/switch_account.json)
现在应该没问题了，感谢配合

**Comment by Loshepherd** [comment]
> [switch_account.json](https://github.com/user-attachments/files/18239576/switch_account.json) 现在应该没问题了，感谢配合

账号选择还有一点问题，会选中退出登录的那个账号，无法实现切换账号功能，log和截图已更新

[Loshepherd/debug](https://github.com/Loshepherd/debug)

**Comment by Windsland52** [comment]
第201行，-150改成-60

**Comment by Loshepherd** [comment]
问题解决了，感谢付出
