### ISSUE TITLE
卡在结算界面无法运行

### ISSUE THREAD

**Issue by cyt0417** [MaaXYZ/M9A#54]
![搜狗高速浏览器截图20231220111326](https://github.com/MaaAssistantArknights/M9A/assets/150600107/ed510e90-632f-4496-9d22-e14cfc711b8a)
![搜狗高速浏览器截图20231220111356](https://github.com/MaaAssistantArknights/M9A/assets/150600107/a23738ac-bb5c-4823-8eef-7b4b251926e9)

**Comment by MistEO** [comment]
模拟器的问题，升级试试，应该是偶现的
