### ISSUE TITLE
每日心相只打一次相关疑问

### ISSUE THREAD

**Issue by longshensanjie** [MaaXYZ/M9A#60]
如上所说，每天可免费打两次，现在的每日心相功能只能打一次，使用时候是需要添加两次吗，能否直接整合到一起，直接打两次，像打普通关卡检查体力一样，自动识别当前可免费打的次数，有几次免费打几次最好，另外也看到前面有人提到，是否把体力刷心相作为一个单独的功能提供出来，最后感谢作者的辛苦付出

**Comment by MistEO** [comment]
就是打两次的呀，会选 x2 的，如果没选可能是 bug，发下 debug/maa.log 看看。

单独刷心相的功能，我自己没啥需求，说实话这个项目我维护的比较少，等个有缘的大佬来带带（

**Comment by MistEO** [comment]
v1.5.0 fixed
