### ISSUE TITLE
收菜时卡在荒原界面不动了

### ISSUE THREAD

**Issue by cyt0417** [MaaXYZ/M9A#64]
![Uploading QQ截图20240213000206.png…]()

**Comment by cyt0417** [comment]
![QQ截图20240213000206](https://github.com/MaaAssistantArknights/M9A/assets/150600107/02fd56d0-19a1-4898-b0f7-bce5262dea08)
![QQ截图20240213000302](https://github.com/MaaAssistantArknights/M9A/assets/150600107/2aabd993-c4ab-4995-b346-4c031b51f159)

**Comment by MistEO** [comment]
试试新版，还不行发一下 debug/maa.log 看看
