### ISSUE TITLE
打开软件并运行肉鸽后软件会自动关闭

### ISSUE THREAD

**Issue by 2352719595** [MaaXYZ/M9A#69]
[maa.log](https://github.com/MaaAssistantArknights/M9A/files/14358228/maa.log)

**Comment by 2352719595** [comment]
![Uploading 屏幕截图 2024-02-21 184848.png…]()

**Comment by MistEO** [comment]
分辨率低了，换 1080p 试试

**Comment by 2352719595** [comment]
还是一样会报错并闪退
![屏幕截图 2024-02-21 205805](https://github.com/MaaAssistantArknights/M9A/assets/90951704/33a546f6-b802-4947-a7ce-3e2a0301add7)
[Uploading maa.log…]()

**Comment by MistEO** [comment]
log 没传上来，重新传一下

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/M9A/assets/18511905/10f1916b-fd7a-4277-80ec-1193b53e7f0a)

可以把 config/maa_toolkit.json 里 save_draw 改成 true，再跑一下。然后打包下 debug 文件夹传一下

**Comment by 2352719595** [comment]
跟你的要求改之后还是出现了问题
![屏幕截图 2024-02-22 124352](https://github.com/MaaAssistantArknights/M9A/assets/90951704/c5d39b42-35c4-4d25-a5db-791e44600994)
[maa.log](https://github.com/MaaAssistantArknights/M9A/files/14368862/maa.log)

**Comment by MistEO** [comment]
打包一下 debug 文件，里面有些图片

**Comment by 2352719595** [comment]
没有看见图片

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/M9A/assets/18511905/539f224a-add6-4306-bd92-340ea35bf0c5)

日志里显示 save_draw 还是关的，看看是不是没改对

**Comment by 2352719595** [comment]
![屏幕截图 2024-02-22 144935](https://github.com/MaaAssistantArknights/M9A/assets/90951704/ef883716-0c02-4e9f-8ce5-16c963338d77)
我这里看是正确的

**Comment by MistEO** [comment]
现在的问题是，所有的图片识别得分都非常低，怀疑是图片质量非常不佳。

这个 save_draw 是把图片保存下来，可以看一看具体是什么情况，不是说改了这个就解决问题了。（但我确实不知道为啥改了没用

建议检查下模拟器设置，有没有调画面风格、亮度等等的，需要全保持默认才行

另外问下是你在游戏哪个界面开始启动 M9A 的？

**Comment by 2352719595** [comment]
我把所有的文件删掉了，重新下载了最新版本所有问题已经正常了，最后感谢大佬
