### ISSUE TITLE
配置好RUN起来就没反应了，看log也没找到哪里的问题

### ISSUE THREAD

**Issue by Do7and** [MaaXYZ/M9A#73]
没有任何输出，也看不到运行到哪个task了，找不到头绪
蓝叠模拟器5.9
![image](https://github.com/MaaXYZ/M9A/assets/41378140/76b863f0-eadc-4060-95ff-d0425903563d)
![image](https://github.com/MaaXYZ/M9A/assets/41378140/c5e55086-e9ea-4907-8044-a72a777b5fd9)

**Comment by MistEO** [comment]
log 文件直接发一下

**Comment by MistEO** [comment]
临时解决方法参考：https://github.com/MaaXYZ/M9A/issues/66#issuecomment-1948109013

**Comment by Do7and** [comment]
解决了，就是截屏方式的问题，谢谢玛丽

**Comment by MistEO** [comment]
所以 log 发一下，不然你每个版本都得手动改（

**Comment by Bl1tzcrank** [comment]
[maa.log](https://github.com/MaaXYZ/M9A/files/14493842/maa.log)
问题一样 解决方法也有效 不知道是不是同一个问题
