### ISSUE TITLE
请问怎么设置MaaPiCli在运行完毕后自动关闭

### ISSUE THREAD

**Issue by SKIE1** [MaaXYZ/M9A#75]
目前需要手动按任意键才能关闭。

我做了个批处理脚本，它会在等待MaaPiCli结束后，关闭模拟器，但是目前卡在了MaaPiCli等待用户按任意键这一步。

**Comment by MistEO** [comment]
使用 1.2.0 及之后版本，启动参数加上 `-d` 即可
