### ISSUE TITLE
游戏卡在面板无法继续

### ISSUE THREAD

**Issue by FuShengACE** [MaaXYZ/M9A#78]
[maa.log](https://github.com/MaaXYZ/M9A/files/14969375/maa.log)
具体情况是M9A自行启动游戏，然后进入看板之后，一直重复点边缘无限循环
![2024-04-14_11-07-54](https://github.com/MaaXYZ/M9A/assets/38291921/abaf8e47-532c-4157-95f6-348179b1374d)

**Comment by MistEO** [comment]
改下模拟器分辨率设置，平板形（而不是手机形
