### ISSUE TITLE
刷完全部体力的选项无法生效

### ISSUE THREAD

**Issue by Loshepherd** [MaaXYZ/M9A#80]
![image](https://github.com/MaaXYZ/M9A/assets/89327296/d4fae177-f0f4-400e-bff6-7db1e54825a2)
结束任务后体力仍未刷完，如图。

**Comment by Loshepherd** [comment]
![image](https://github.com/MaaXYZ/M9A/assets/89327296/5bf4b45b-ba6b-4a58-96ca-b60302fdea41)
config中已开启“刷完全部体力”

**Comment by dongwlin** [comment]
来点log

**Comment by Loshepherd** [comment]
[maa.zip](https://github.com/MaaXYZ/M9A/files/15037654/maa.zip)

**Comment by Loshepherd** [comment]
[maa.log](https://github.com/MaaXYZ/M9A/files/15047661/maa.log)

**Comment by MistEO** [comment]
咋关了
