### ISSUE TITLE
无法运行启动M9A

### ISSUE THREAD

**Issue by neodark152** [MaaXYZ/M9A#82]
程序无法启动，打开MaaPiCli.exe文件后cmd窗口启动几秒后关闭，然后就没反应了....
![111](https://github.com/MaaXYZ/M9A/assets/110011234/595486fc-d040-46b1-95d9-89682f6827cb)

**Comment by Impregnabl-e** [comment]
> 程序无法启动，打开MaaPiCli.exe文件后cmd窗口启动几秒后关闭，然后就没反应了.... ![111](https://private-user-images.githubusercontent.com/110011234/326245623-595486fc-d040-46b1-95d9-89682f6827cb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzI1MzYsIm5iZiI6MTcxNTIzMjIzNiwicGF0aCI6Ii8xMTAwMTEyMzQvMzI2MjQ1NjIzLTU5NTQ4NmZjLWQwNDAtNDZiMS05NWQ5LTg5NjgyZjY4MjdjYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwNTIzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDhkODI5NGNlMzI3MTlhM2ExNzZmMjFjOTFmZDBlN2Q0MTQyNmNjNmMzOWJjNWQ0OTc3NjExOTBiNTQ4YjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uRE-j5fy3T5agLow0wxfe9ULA4DeiKxQXmUXBzvY1BI)

我也遇到了这个问题：（

**Comment by MistEO** [comment]
1. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98

2. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%AE%98%E6%96%B9%E6%95%B4%E5%90%88%E5%8C%85-%E7%A1%AE%E4%BF%A1

照这两个方法试一下

**Comment by Impregnabl-e** [comment]
> 1. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98
> 2. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%AE%98%E6%96%B9%E6%95%B4%E5%90%88%E5%8C%85-%E7%A1%AE%E4%BF%A1
> 
> 照这两个方法试一下
还是没有成功......
![image](https://github.com/MaaXYZ/M9A/assets/169332898/617aa0af-6b62-4186-b7aa-df2bd4aa6cb6)
我又下载了这些，重启后仍然打开会闪退：（

**Comment by Impregnabl-e** [comment]
> 1. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98
> 2. https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%AE%98%E6%96%B9%E6%95%B4%E5%90%88%E5%8C%85-%E7%A1%AE%E4%BF%A1
> 
> 照这两个方法试一下

佬，菜菜，捞捞    ：（

**Comment by MistEO** [comment]
vs_BuildTools 里面 C++ 那个已经装过了？

![image](https://github.com/MaaXYZ/M9A/assets/18511905/ff9fa800-112e-4799-ab1f-60fc4f93388b)

**Comment by MistEO** [comment]
😥那我也不知道还缺啥了，懵了

**Comment by MistEO** [comment]
排查到了一个可能的原因是文件夹中有中文或者空格，换个目录试试
