### ISSUE TITLE
怎么实现MAA和M9A同时运行？

### ISSUE THREAD

**Issue by BitaMatt** [MaaXYZ/M9A#91]
![image](https://github.com/MaaXYZ/M9A/assets/52351304/ededc1be-d073-487f-81f0-cc2cd672773c)
如果MAA(adb连接的是蓝叠国内版
![image](https://github.com/MaaXYZ/M9A/assets/52351304/c9848bbb-7e80-43a9-9313-ca296135535c)
）和M9A（adb连接的是mumu12
![image](https://github.com/MaaXYZ/M9A/assets/52351304/42fc101e-1ce1-480a-bac7-1f9fce2220f1)
）同时运行时M9A会出现错误，然后MAA会显示连接失败
![image](https://github.com/MaaXYZ/M9A/assets/52351304/04537dec-20e4-41d8-9d6b-c5c8aec859d2)

但是明明两者连接的ADB和使用的模拟器都不一样，为什么会出现问题？

**Comment by dongwlin** [comment]
好神奇

**Comment by MistEO** [comment]
就是因为用的 adb 不一样才会出问题

你试试用 mumu 或者蓝叠的多开，用同一个模拟器

**Comment by Yanzzl** [comment]
![image](https://github.com/MaaXYZ/M9A/assets/40536490/d95816f1-f8ea-4fa0-8fd2-26bdd5f157d1)
使用多开器给每个游戏固定adb接口就可以了。如果不使用多开器，那么他的接口会从16384开始计数，下一个打开的模拟器为16385，依次类推。

**Comment by MistEO** [comment]
> ![image](https://private-user-images.githubusercontent.com/40536490/332570374-d95816f1-f8ea-4fa0-8fd2-26bdd5f157d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDgyNjUsIm5iZiI6MTcxNjM0Nzk2NSwicGF0aCI6Ii80MDUzNjQ5MC8zMzI1NzAzNzQtZDk1ODE2ZjEtZjhlYS00ZmEwLThmZDItMjZiZGQ1ZjE1N2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzEwYWFlN2E2NjI3OTEyYzc3Y2ZlZmMyZWFmZDI3MzJiYjE3NzdhNGU5MjZmODEzMDI2MDI3YTM1M2Y5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4Or3as0AeigkueblW-0sroUkotNLw5-uLoHuREaVRM) 使用多开器给每个游戏固定adb接口就可以了。如果不使用多开器，那么他的接口会从16384开始计数，下一个打开的模拟器为16385，依次类推。

mumu 是每次 +16，不是+1
