### ISSUE TITLE
Bug：最新版本荒原无法收取金色材料

### ISSUE THREAD

**Issue by longshensanjie** [MaaXYZ/M9A#93]
在最新 1.4 版本里荒原收取金色材料失败

**Comment by MistEO** [comment]
发下 log

**Comment by longshensanjie** [comment]
[Uploading maa.log…]()

**Comment by longshensanjie** [comment]
[Uploading maa.log…]()

**Comment by longshensanjie** [comment]
[Uploading maa.log…]()

**Comment by longshensanjie** [comment]
[maa.zip](https://github.com/MaaXYZ/M9A/files/15397510/maa.zip)

**Comment by longshensanjie** [comment]
ps：另外发现新版本的点唱机奖励也不会领取
