### ISSUE TITLE
近期修改点击START的识别方式后无法启动

### ISSUE THREAD

**Issue by SHAventurine** [MaaXYZ/M9A#94]
[maa.log](https://github.com/MaaXYZ/M9A/files/15400597/maa.log)
1.3.1更新之后用1.3.1和1.4启动游戏都会卡在START界面或者反复出现白底“深蓝互动”的加载界面，手动点START之后也不会继续运行。用1.2的话有的时候能启动有的时候不能，虽然手动点START之后会继续运行，但是收取奖励的时候不会收新版本的点唱机。
提交的log是使用1.4版本的。
我自己尝试看了一下文件和更新的commit但是完全看不懂，对不起我是电脑白痴打扰各位大佬了。如果还有什么需要我提供的请告诉我，非常感激！

**Comment by a16797** [comment]
你的登录界面 截个图看看

**Comment by Kaminingyo** [comment]
![MuMu12-20240523-163338](https://github.com/MaaXYZ/M9A/assets/104976150/817c30a1-5580-454c-b2d5-66b2adbab682)
同样的问题，这个样子

**Comment by MistEO** [comment]
@Tohkahb 来瞅瞅？

**Comment by a16797** [comment]
> ![MuMu12-20240523-163338](https://private-user-images.githubusercontent.com/104976150/333107360-817c30a1-5580-454c-b2d5-66b2adbab682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjU4NDUsIm5iZiI6MTcxNjUyNTU0NSwicGF0aCI6Ii8xMDQ5NzYxNTAvMzMzMTA3MzYwLTgxN2MzMGExLTU1ODAtNDU0Yy1iMmQ1LTY2YjJhZGJhYjY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNDM5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTEzZWM3NWM0NTk5MDIyMjYzMGViZDAwYmM3ZTc5ZDhkM2FkNzRlZTFkMmEzNzQ0NjA5NjFlZmU3ODA5ZDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kqML6PEcMqBF0Pv8DZ5KCEAWvIpq4X06Aa7uSNUv054) 同样的问题，这个样子

你的日志发个瞅瞅

**Comment by a16797** [comment]
点唱机是要修改一下

**Comment by Kaminingyo** [comment]
[maa.log](https://github.com/MaaXYZ/M9A/files/15436836/maa.log)
是这个吧

**Comment by MistEO** [comment]
fixed
